on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
        
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output ./publish
    - name: Push1
      run: dotnet nuget push ./publish/Cygna.MapLookupGen.${VERSION}.nupkg --skip-duplicate -n --api-key "${{ secrets.GITHUB_TOKEN }}"
    - name: Push2
      run: dotnet nuget push ./publish/Cygna.MapLookupGen.Core.${VERSION}.nupkg --skip-duplicate -n --api-key "${{ secrets.GITHUB_TOKEN }}"
    - name: Push3
      run: dotnet nuget push ./publish/Cygna.MapLookupGen.Generator.${VERSION}.nupkg --skip-duplicate -n --api-key "${{ secrets.GITHUB_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
