on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          10.0.x
    - name: Set VERSION variable from tag
      run: |
        $VERSION=$Env:GITHUB_REF_NAME.TrimStart("v")
        echo "VERSION=$VERSION" >> $Env:GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=$Env:VERSION
    - name: Test
      run: dotnet test --configuration Release /p:Version=$Env:VERSION --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=$Env:VERSION --no-build --output ./publish
    - name: Push1
      run: dotnet nuget push ./publish/Cygna.MapLookupGen.$Env:VERSION.nupkg --skip-duplicate -n --api-key "${{ secrets.GITHUB_TOKEN }}"
    - name: Push2
      run: dotnet nuget push ./publish/Cygna.MapLookupGen.Core.$Env:VERSION.nupkg --skip-duplicate -n --api-key "${{ secrets.GITHUB_TOKEN }}"
    - name: Push3
      run: dotnet nuget push ./publish/Cygna.MapLookupGen.Generators.$Env:VERSION.nupkg --skip-duplicate -n --api-key "${{ secrets.GITHUB_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
